pipeline {
   agent any
   stages {
     stage('Build'){
          steps{
            sh 'touch kranthi'
}
}
      stage('Test'){
          steps{
            sh 'touch varma'
}
}
      stage('Deploy') {
         steps{
           sh 'touch bujikonda'
}   
}
}
}

