pipeline {
   agent any
   stages {
     stage('Build'){
          steps{
            sh 'touch file1'
}
}
      stage('Test'){
          steps{
            sh 'touch file2'
}
}
      stage('Deploy') {
         steps{
           sh 'touch file3'
}   
}
}
}

